Repository integritee-network/worker, pull requests merged in 2023-02, with the labels that each got.

#1163 GHA: always run integration-tests even if unit tests failed
  .github/workflows/build_and_test.yml
Labels: B0-silent, C1-low 📌, E0-breaksnothing, A7-somethingelse

#1160 fix potential polkadot-v0.9.37 dependency leak after cargo update
  Cargo.lock
  app-libs/sgx-runtime/Cargo.toml
  app-libs/stf/Cargo.toml
  cli/Cargo.toml
  enclave-runtime/Cargo.lock
  service/Cargo.toml
Labels: B1-releasenotes, C1-low 📌, E0-breaksnothing, A7-somethingelse

#1161 Cargo update
  Cargo.lock
  Makefile
  enclave-runtime/Cargo.lock
Labels: B0-silent, C1-low 📌, E0-breaksnothing, A7-somethingelse

#1164 Replace dockerize with built-in healthcheck
  .github/workflows/build_and_test.yml
  Cargo.lock
  Dockerfile
  build.Dockerfile
  docker/README.md
  docker/demo-direct-call.yml
  docker/demo-indirect-invocation.yml
  docker/demo-sidechain.yml
  docker/demo-smart-contract.yml
  docker/demo-teeracle-generic.yml
  docker/demo-teeracle.yml
  docker/docker-compose.yml
  docker/fork-inducer.yml
  docker/sidechain-benchmark.yml
Labels: B1-releasenotes, C1-low 📌, E0-breaksnothing, A7-somethingelse

#1155 Refactoring attempt for indirect-calls-executor
  core/parentchain/indirect-calls-executor/src/executor/call_worker.rs
  core/parentchain/indirect-calls-executor/src/executor/mod.rs
  core/parentchain/indirect-calls-executor/src/executor/shield_funds.rs
  core/parentchain/indirect-calls-executor/src/indirect_calls_executor.rs
  core/parentchain/indirect-calls-executor/src/lib.rs
Labels: A0-core, B1-releasenotes, C1-low 📌, E0-breaksnothing

#1169 Do not error out when searching peers
  service/src/worker.rs
Labels: A3-sidechain, B1-releasenotes, C1-low 📌, E0-breaksnothing

#1173 Bump to polkadot-v0.9.37
  Cargo.lock
  app-libs/sgx-runtime/Cargo.toml
  app-libs/stf/Cargo.toml
  app-libs/stf/src/stf_sgx.rs
  cli/Cargo.toml
  core-primitives/attestation-handler/Cargo.toml
  core-primitives/enclave-api/Cargo.toml
  core-primitives/extrinsics-factory/Cargo.toml
  core-primitives/hashing/Cargo.toml
  core-primitives/node-api/api-client-extensions/Cargo.toml
  core-primitives/node-api/api-client-types/Cargo.toml
  core-primitives/node-api/factory/Cargo.toml
  core-primitives/node-api/metadata/Cargo.toml
  core-primitives/ocall-api/Cargo.toml
  core-primitives/sgx-runtime-primitives/Cargo.toml
  core-primitives/sgx/crypto/Cargo.toml
  core-primitives/stf-executor/Cargo.toml
  core-primitives/stf-primitives/Cargo.toml
  core-primitives/stf-state-handler/Cargo.toml
  core-primitives/storage/Cargo.toml
  core-primitives/substrate-sgx/externalities/Cargo.toml
  core-primitives/substrate-sgx/sp-io/Cargo.toml
  core-primitives/substrate-sgx/sp-io/src/lib.rs
  core-primitives/teerex-storage/Cargo.toml
  core-primitives/test/Cargo.toml
  core-primitives/top-pool-author/Cargo.toml
  core-primitives/top-pool/Cargo.toml
  core-primitives/types/Cargo.toml
  core-primitives/utils/Cargo.toml
  core/direct-rpc-server/Cargo.toml
  core/offchain-worker-executor/Cargo.toml
  core/parentchain/block-import-dispatcher/Cargo.toml
  core/parentchain/block-importer/Cargo.toml
  core/parentchain/indirect-calls-executor/Cargo.toml
  core/parentchain/light-client/Cargo.toml
  core/parentchain/parentchain-crate/Cargo.toml
  core/parentchain/test/Cargo.toml
  core/rpc-client/Cargo.toml
  core/rpc-server/Cargo.toml
  core/tls-websocket-server/Cargo.toml
  enclave-runtime/Cargo.lock
  enclave-runtime/Cargo.toml
  service/Cargo.toml
  sidechain/block-composer/Cargo.toml
  sidechain/block-verification/Cargo.toml
  sidechain/consensus/aura/Cargo.toml
  sidechain/consensus/common/Cargo.toml
  sidechain/consensus/slots/Cargo.toml
  sidechain/primitives/Cargo.toml
  sidechain/rpc-handler/Cargo.toml
  sidechain/state/Cargo.toml
  sidechain/storage/Cargo.toml
  sidechain/test/Cargo.toml
  sidechain/validateer-fetch/Cargo.toml
Labels: B1-releasenotes, C1-low 📌, E3-hardmerge, A7-somethingelse

#1174 Add a proof of execution to shield funds trusted call
  app-libs/stf/src/trusted_call.rs
  core-primitives/node-api/metadata/src/metadata_mocks.rs
  core-primitives/node-api/metadata/src/pallet_teerex.rs
  docker/docker-compose.yml
Labels: A2-applibs, B1-releasenotes, C1-low 📌, E6-parentchain

#1182 Several improvements for the local-setup
  local-setup/README.md
  local-setup/config/benchmark.json
  local-setup/config/one-worker.json
  local-setup/config/two-workers.json
  local-setup/github-action-config.json
  scripts/benchmark_local-setup.sh
Labels: B1-releasenotes, C1-low 📌, E5-publicapi, A7-somethingelse

#1159 Fetch quotes from Marblerun Prometheus REST API endpoint
  Cargo.lock
  app-libs/stf/Cargo.toml
  cli/Cargo.toml
  core-primitives/enclave-api/ffi/src/lib.rs
  core-primitives/enclave-api/src/remote_attestation.rs
  core/rest-client/src/rest_client.rs
  enclave-runtime/Cargo.lock
  enclave-runtime/Enclave.edl
  enclave-runtime/src/attestation.rs
  service/Cargo.toml
  service/src/config.rs
  service/src/main.rs
  service/src/prometheus_metrics.rs
  service/src/utils.rs
Labels: A5-teeracle, A0-core, A1-cli, B1-releasenotes, C1-low 📌, E0-breaksnothing

#1184 Fix tests and CI
  .github/workflows/build_and_test.yml
  app-libs/stf/src/stf_sgx_tests.rs
  enclave-runtime/src/test/enclave_signer_tests.rs
  enclave-runtime/src/test/tests_main.rs
Labels: B0-silent, C1-low 📌, E0-breaksnothing, A7-somethingelse

#1185 Reduce docker image size
  build.Dockerfile
Labels: B0-silent, C1-low 📌, E0-breaksnothing, A7-somethingelse
